me {
name "irc.local";
info "unrealircd over i2p";
sid "001";
};

admin {
"admin";
"admin";
"contact: admin@local";
};

include "modules.default.conf";
include "help/help.conf";
include "badwords.conf";
include "operclass.default.conf";
include "snomasks.default.conf";

loadmodule "cloak_sha256";

class clients {
pingfreq 90;
maxclients 1000;
sendq 200k;
recvq 8000;
};

class opers {
    pingfreq 90;
    maxclients 50;
    sendq 1M;
    recvq 8000;
};

allow {
mask *;
class clients;
maxperip 3;
};

oper admin {
class opers;
mask *@127.0.0.1;
password "$argon2id$putyourcustomargon2idhashhere";
operclass netadmin;
};


listen {
    ip 127.0.0.1;
    port 6667;
};

listen {
    ip 127.0.0.1;
    port 6697;
    options { tls; };
};


set {
    network-name "i2pnet";
    default-server "127.0.0.1";
    help-channel "help channel here. default #help";
    kline-address "put an email or an url here";

    cloak-keys {
        "clock key number 1 here";
        "clock key number 2 here";
        "clock key number 3 here";
    };
    options {
        hide-ulines;
    };

};

